### PR TITLE
Add slack & use bootstrap rows over image-height formatting.

### PR DESCRIPTION
**Pull request by teh**

### CODE REVIEW

**Comment by teh** [comment]
Apologies, removed your message. I removed the jira reference altogether. I feel there are sufficient links to the GH projects (e.g. on hackage), that people will figure it out. It's not like the target audience isn't technical.

**Comment by hyperthunk** [comment]
Agreed!

**Comment by hyperthunk** [comment]
Have we not merged this yet...? Apologies I'll get it sorted asap

**Comment by facundominguez** [comment]
Ping @hyperthunk

**Pull request merged**
